Create NavItem Component
jorgecarmona/ci-next-hr pull request #24
Opened 2024-05-30 19:21 UTC by SGutierrez17

### Component
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/0e3ba5f0-8b70-4bd2-8672-506585b52f0f)

### Storybook
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/a94523f4-d965-49f7-a768-62ac80c840fb)
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/8f932bfa-d1ae-4084-9e01-18cdf22b52e4)

### Coverage
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/9f03ade8-f46b-4d3c-b8c9-c095f49a3554)

2024-05-31 02:31 UTC, jorgecarmona commented on src/stories/molecules/navItem.stories.tsx
> +    title: 'Atoms/NavItem',
debe ser:

`title: 'Molecules/NavItem'`

2024-05-31 13:24 UTC, napito27 reviewed
left you some comments

2024-05-31 13:24 UTC, napito27 commented on src/molecules/navItem.tsx
> +                    {title}
maybe add `{title.toUpperCase()}` para que siempre se muestre asi, aunque no te lo pasen siempre en mayusculas

2024-05-31 13:24 UTC, napito27 commented on src/molecules/navItem.tsx
> +function NavItem({icon, selected, onClickCallBack, title = ''} :NavItemProps){
si el `title` no es opcional no creo que necesite un default value

2024-05-31 13:24 UTC, napito27 commented on src/molecules/navItem.tsx
> +import React from "react";
podrias borrar en codigo que no se esta usando.

2024-05-31 13:24 UTC, napito27 commented on src/atoms/icon-store.ts
> +  Person2 = "person2",
como observacion, talves podrias llavar los icon  `person` y `trending` mejor.

2024-05-31 18:04 UTC, paulagutierrez08 commented on src/stories/molecules/navItem.stories.tsx
> +    title: 'Atoms/NavItem',
Corregido!

2024-05-31 18:04 UTC, paulagutierrez08 commented on src/molecules/navItem.tsx
> +                    {title}
Corregido!

2024-05-31 18:05 UTC, paulagutierrez08 commented on src/molecules/navItem.tsx
> +import React from "react";
Corregido!

2024-05-31 18:05 UTC, paulagutierrez08 commented on src/atoms/icon-store.ts
> +  Person2 = "person2",
Ingeniero Napo realicé la modificación de person, sin embargo la de trending no, ya que considero que si es una tendencia hacia arriba

2024-05-31 18:06 UTC, paulagutierrez08 commented on src/molecules/navItem.tsx
> +function NavItem({icon, selected, onClickCallBack, title = ''} :NavItemProps){
Corregido!

2024-05-31 19:33 UTC, napito27 approved these changes

2024-06-02 19:30 UTC, IngridVillaba approved these changes

2024-06-03 18:56 UTC, paulagutierrez08 approved these changes

2024-06-03 23:52 UTC, jorgecarmona commented
este componente tiene conflictos. Arreglar por favor

2024-06-04 00:08 UTC, paulagutierrez08 commented
@jorgecarmona Ya he arreglado el conflicto arquitecto

2024-06-04 00:37 UTC, jorgecarmona requested changes

2024-06-04 00:37 UTC, jorgecarmona commented on src/atoms/icon-store.ts
> +  Person2 = "person",
no debemos usar numeros aqui. Cambia por `Person`

2024-06-04 00:37 UTC, jorgecarmona commented on src/atoms/icon-store.ts
> +  person2: Person2Outlined,
cambiar por `person`

2024-06-04 04:06 UTC, paulagutierrez08 commented on src/atoms/icon-store.ts
> +  person2: Person2Outlined,
Corregido!

2024-06-04 04:06 UTC, paulagutierrez08 commented on src/atoms/icon-store.ts
> +  Person2 = "person",
Corregido!

2024-06-06 03:09 UTC, jorgecarmona approved these changes

2024-06-06 03:12 UTC, merged