Creation of Buttons Toolbar Component
jorgecarmona/ci-next-hr pull request #25
Opened 2024-05-31 19:24 UTC by napito27

# ButtonsToolbar
![image](https://github.com/jorgecarmona/ci-next-hr/assets/137454549/bb66be30-b3f9-4eac-a62a-b03fcdb4d476)
![image](https://github.com/jorgecarmona/ci-next-hr/assets/137454549/2f1dee72-a86a-43ee-8713-aeb915235e6d)

# Stories
![Screenshot 2024-05-30 160238](https://github.com/jorgecarmona/ci-next-hr/assets/137454549/36dfd4a8-c495-4c7f-b7d0-86f959ee2130)

2024-05-31 22:30 UTC, jorgecarmona requested changes

2024-05-31 22:30 UTC, jorgecarmona commented on src/__tests__/molecules/buttons-toolbar.test.tsx
> +    expect(button1).toBeInTheDocument();
we need breaklines between expect and const

2024-05-31 22:30 UTC, jorgecarmona commented on src/__tests__/molecules/buttons-toolbar.test.tsx
> +    const spanElement = document.querySelector('span[style*="border-bottom: 1px solid #175CD3"]');
better to set a `data-testid`

https://testing-library.com/docs/queries/bytestid/

2024-06-01 00:48 UTC, SGutierrez17 commented on src/molecules/buttons-toolbar.tsx
> +    <>
ingeniero aqui puedes eliminar <> no se hace necesario si el padre es el <Stack>

2024-06-01 00:49 UTC, SGutierrez17 commented on src/stories/molecules/buttons-toolbar.stories.tsx
> +import {fn} from "@storybook/test";
No se esta usando la función fn

2024-06-01 00:50 UTC, SGutierrez17 requested changes
Ingeniero buenas noches, te hice unos comentarios !

2024-06-02 23:26 UTC, SGutierrez17 approved these changes

2024-06-02 23:29 UTC, juanav22 approved these changes

2024-06-03 23:54 UTC, jorgecarmona commented
@napito27 arreglar los conflictos por favor

2024-06-06 03:13 UTC, jorgecarmona commented
@napito27 resolver conflictos por favor

2024-06-06 05:04 UTC, jorgecarmona commented
@napito27 Test is failing
![image](https://github.com/jorgecarmona/ci-next-hr/assets/15080066/cbdad739-334e-4433-89e0-d3fbc73fd4fc)

2024-06-06 05:37 UTC, jorgecarmona approved these changes

2024-06-06 05:38 UTC, merged