create login page
jorgecarmona/ci-next-hr pull request #26
Opened 2024-06-02 18:48 UTC by davidc0326

creation of login page to be incorporated to the layout component 
![image](https://github.com/jorgecarmona/ci-next-hr/assets/137354680/dc29e8ee-3844-46c3-a893-3dad54a6be9c)
![image](https://github.com/jorgecarmona/ci-next-hr/assets/137354680/c177d0d3-ad60-4587-932f-d9f21cb47ed0)
![image](https://github.com/jorgecarmona/ci-next-hr/assets/137354680/5a2b4827-0076-4365-84ca-429ea17fe1b2)
![image](https://github.com/jorgecarmona/ci-next-hr/assets/137354680/1c8e5224-aada-4607-842f-8fcc9eed004e)

2024-06-02 19:52 UTC, NancyBlancoS approved these changes

2024-06-02 20:16 UTC, SGutierrez17 commented on src/pages/login.tsx
> +import React, {useState, CSSProperties} from "react";
Ingeniero las importaciones de react y cssproperties es necesario hacerlas, recuerda como hacemos para usar useState..
React.useState

2024-06-02 20:17 UTC, SGutierrez17 requested changes
Ingeniero buenas tardes, te deje un comentario, pero antes de solucionarlo tienes conflictos por resolver con github.

2024-06-03 00:56 UTC, davidc0326 commented on src/pages/login.tsx
> +import React, {useState, CSSProperties} from "react";
ingeniero ya se hicieron correciones sugeridas.

2024-06-03 16:26 UTC, SGutierrez17 approved these changes

2024-06-03 23:34 UTC, merged