Hr-108-create-password-component
jorgecarmona/ci-next-hr pull request #3
Opened 2024-05-13 19:25 UTC by SGutierrez17

Default
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/b2a7c609-724e-431d-bf38-27a7daaf7cde)

Error
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/a4b5baef-942b-45be-b900-681993aab288)

Icon
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/20bf74af-a342-499b-8711-c38ca478fd7b)

2024-05-14 19:33 UTC, SGutierrez17 commented
Storybook 
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/f0461c84-f6c6-4f34-b500-05dd20d98c5e)


Coverage 
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/64714cd8-e8ec-4095-b8ae-3454e29f6ff8)

2024-05-15 00:38 UTC, SGutierrez17 commented
Error
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/61a4b08c-6e3a-431b-a68c-6ebd62dd5506)

2024-05-17 01:13 UTC, SGutierrez17 commented
Correction label 
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/e06aa739-cd9b-4f2b-9e2f-1776ac2b1fb8)

2024-05-17 12:39 UTC, NancyBlancoS approved these changes

2024-05-17 16:11 UTC, OskarMantilla21 approved these changes
revicion realizada y tarea terminada con exito

2024-05-21 16:03 UTC, jorgecarmona commented
@OskarMantilla21 @NancyBlancoS @SGutierrez17   Este PR se aprobo pero tiene 75% de coverage en una parte. Quedamos que era minimo 80%.

2024-05-21 16:04 UTC, jorgecarmona commented
Este componente debe funcionar con el form para el submit, ya probamos eso?

2024-05-22 00:05 UTC, SGutierrez17 commented
Unit Test Coverage
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/5611be6a-87cd-4fe2-8fcc-dd9d392383cf)

Storybook
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/9dfb129c-690d-4979-9ba8-f628b597d139)

2024-05-27 03:43 UTC, jorgecarmona requested changes
Un pequeno comentario

2024-05-27 03:43 UTC, jorgecarmona commented on src/stories/atoms/password.stories.tsx
> +export const Default : StoryObj<typeof PasswordTextField> = {
Crear un type aqui para no tener que repetir el type en cada caso de uso.

```
type Story =  StoryObj<type of meta>;

export const Default : Story = {...}
```

2024-05-27 04:12 UTC, SGutierrez17 commented on src/stories/atoms/password.stories.tsx
> +export const Default : StoryObj<typeof PasswordTextField> = {
bueno si señor, ya lo cambio

2024-05-27 22:47 UTC, jorgecarmona approved these changes

2024-05-27 22:48 UTC, merged