Creation text field component
jorgecarmona/ci-next-hr pull request #6
Opened 2024-05-17 02:07 UTC by SGutierrez17

## Component
#### Default textField
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/6866edbf-0095-4f36-b79c-e6f5fd61fd8e)

#### TextField with Icon
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/91c328b8-5d52-4c19-b2fe-ae15258aded0)

#### Read-Only TextField 
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/1ad76e1c-d154-46a7-850d-e1d47cd12d8e)

#### TextField with Errors
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/c1fc5b77-f08f-43c5-905e-0861cfa740ac)

## StoryBook
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/12666e44-6f7f-4961-a89f-4c70cb8bb0ff)

## Unit Test
![image](https://github.com/jorgecarmona/ci-next-hr/assets/136516495/fe507f5b-a57a-4cf2-b80b-09d1bf9e1477)

2024-05-20 22:07 UTC, davidc0326 commented on src/atoms/textField.tsx
> +interface TextFieldProps{
ingeniero las propiedades deberian de estar en orden alfabetico.

2024-05-20 22:17 UTC, davidc0326 commented on src/atoms/textField.tsx
> +            <InputLabel required={false} style={{paddingLeft:"10px"}}>
en esta parte no se deberia utilizar el htmlfor

2024-05-20 22:24 UTC, davidc0326 commented on src/__tests__/atoms/textField.test.tsx
> +        const labelElement = screen.getByText(/Name/i);
asegurac de dejar unsalto de linea despues de cada render

2024-05-20 22:26 UTC, davidc0326 reviewed
Ingeniero deje comentarios

2024-05-23 21:00 UTC, juanav22 commented on src/atoms/textField.tsx
> +import {TextField as MuiTextField, IconButton, InputAdornment, InputLabel } from "@mui/material";
Ingeniera debes de importar React

2024-05-23 21:00 UTC, juanav22 commented on src/atoms/textField.tsx
>  }
ingeniera recuerda dejar un salto de linea

2024-05-23 21:00 UTC, juanav22 commented on src/atoms/textField.tsx
> +
ingeniera aca puedes quitar este espacio

2024-05-23 21:00 UTC, juanav22 commented on src/pages/playground.tsx
> +      <h1>PlayGround</h1>
recuerda que este archivo no debe de subirse

2024-05-23 21:00 UTC, juanav22 commented on src/__tests__/atoms/textField.test.tsx
>  describe("TextField Component", () => {
Asegurate que todas las pruebas estén dentro del bloque **"describe"**

2024-05-23 22:55 UTC, davidc0326 requested changes
las pruebas unitarias estan funcionando bien solo tiene que hacer el salto de linea  donde termina  render. !!Buen trabajo Ingeniera!!!

2024-05-24 03:07 UTC, SGutierrez17 commented on src/atoms/textField.tsx
> +interface TextFieldProps{
corregido!

2024-05-24 03:08 UTC, SGutierrez17 commented on src/atoms/textField.tsx
> +            <InputLabel required={false} style={{paddingLeft:"10px"}}>
ingeniero pero para la prueba unitaria se hace requerido, debido a esto se uno el htmlFor

2024-05-24 03:09 UTC, SGutierrez17 commented on src/__tests__/atoms/textField.test.tsx
> +        const labelElement = screen.getByText(/Name/i);
corregido!

2024-05-24 03:10 UTC, SGutierrez17 commented on src/atoms/textField.tsx
> +import {TextField as MuiTextField, IconButton, InputAdornment, InputLabel } from "@mui/material";
ingeniera como no se esta usando react no lo vi necesario dejarlo

2024-05-24 03:10 UTC, SGutierrez17 commented on src/atoms/textField.tsx
>  }
corregido!

2024-05-24 03:12 UTC, SGutierrez17 commented on src/pages/playground.tsx
> +      <h1>PlayGround</h1>
ingeniera me parece raro, porque en mi componente no tengo nada de TextField Password, el playground esta como se realizo desde un principio.

2024-05-24 03:13 UTC, SGutierrez17 commented on src/__tests__/atoms/textField.test.tsx
>  describe("TextField Component", () => {
corregido!

2024-05-26 18:50 UTC, juanav22 approved these changes

2024-05-26 20:49 UTC, davidc0326 approved these changes
Buen trabajo

2024-05-27 03:46 UTC, jorgecarmona requested changes
Pequeno comentario, una vez arreglado puedes hacer el merge

2024-05-27 03:46 UTC, jorgecarmona commented on src/stories/atoms/textField.stories.tsx
Crear un type aqui para no tener que repetir el type en cada caso de uso.
```
type Story =  StoryObj<type of meta>;

export const Default : Story = {...}
```

2024-05-27 04:06 UTC, SGutierrez17 commented on src/stories/atoms/textField.stories.tsx
si señor, voy hacer el cambio

2024-05-27 04:39 UTC, paulagutierrez08 commented on src/stories/atoms/textField.stories.tsx
Corregido Arquitecto!

2024-05-27 04:40 UTC, paulagutierrez08 approved these changes

2024-05-28 00:25 UTC, jorgecarmona approved these changes

2024-05-28 01:15 UTC, merged